config/routes.rb
Rails.application.routes.draw do
  root_controller = 'cms/pages#home'
  root root_controller
  # match '/*' => root_controller, via: :options
  namespace :onboardings do
    resources :objectives do
      resources :tour_steps, only: [:index, :show]
    end
    resources :steps
  end
  namespace :cms do
    resources :pages do
      collection do
        get :home
      end
    end
  end
  namespace :news do
    resources :posts
  end
  namespace :media_center do
    resources :files
  end
  
  get "sessions/create"
  get "sessions/destroy"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/onboardings.rb
module Onboardings
  def self.table_name_prefix
    "onboardings_"
  end
end

app/models/onboardings/objective.rb
class Onboardings::Objective < ApplicationRecord
  has_many :steps, dependent: :destroy

  validates :name, :description, presence: true
end

app/models/onboardings/step.rb
class Onboardings::Step < ApplicationRecord
  belongs_to :objective
  belongs_to :resource, polymorphic: true

  validates :objective, :resource, presence: true

  def resource_global_id
    self.resource&.to_global_id
  end

  def resource_global_id=(global_id)
    self.resource = GlobalID::Locator.locate global_id
  end
end

app/controllers/onboardings/objectives_controller.rb
class Onboardings::ObjectivesController < ApplicationController
  
  before_action do
    redirect_to '/', alert: 'you cannot access this page' unless current_user.admin?
  end
  
  before_action :set_onboardings_objective, only: %i[ show edit update destroy ]

  # GET /onboardings/objectives or /onboardings/objectives.json
  def index
    @onboardings_objectives = Onboardings::Objective.all
  end

  # GET /onboardings/objectives/1 or /onboardings/objectives/1.json
  def show
  end

  # GET /onboardings/objectives/new
  def new
    @onboardings_objective = Onboardings::Objective.new
  end

  # GET /onboardings/objectives/1/edit
  def edit
  end

  # POST /onboardings/objectives or /onboardings/objectives.json
  def create
    @onboardings_objective = Onboardings::Objective.new(onboardings_objective_params)

    respond_to do |format|
      if @onboardings_objective.save
        format.html { redirect_to edit_onboardings_objective_url(@onboardings_objective), notice: "Objective was successfully created." }
        format.json { render :show, status: :created, location: @onboardings_objective }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @onboardings_objective.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /onboardings/objectives/1 or /onboardings/objectives/1.json
  def update
    respond_to do |format|
      if @onboardings_objective.update(onboardings_objective_params)
        format.html { redirect_to edit_onboardings_objective_url(@onboardings_objective), notice: "Objective was successfully updated." }
        format.json { render :show, status: :ok, location: @onboardings_objective }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @onboardings_objective.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /onboardings/objectives/1 or /onboardings/objectives/1.json
  def destroy
    @onboardings_objective.destroy

    respond_to do |format|
      format.html { redirect_to onboardings_objectives_url, notice: "Objective was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_onboardings_objective
      @onboardings_objective = Onboardings::Objective.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def onboardings_objective_params
      params.require(:onboardings_objective).permit(:name, :description, :finished_message)
    end
end

app/controllers/onboardings/steps_controller.rb
class Onboardings::StepsController < ApplicationController

  before_action do
    redirect_to '/', alert: 'you cannot access this page' unless current_user.admin?
  end
  
  before_action :set_onboardings_step, only: %i[ show edit update destroy ]

  # GET /onboardings/steps or /onboardings/steps.json
  def index
    @onboardings_steps = Onboardings::Step.all
  end

  # GET /onboardings/steps/1 or /onboardings/steps/1.json
  def show
  end

  # GET /onboardings/steps/new
  def new
    @onboardings_objective = Onboardings::Objective.find(params[:parent_objective_id])
    @onboardings_step = @onboardings_objective.steps.build
  end

  # GET /onboardings/steps/1/edit
  def edit
  end

  # POST /onboardings/steps or /onboardings/steps.json
  def create
    @onboardings_step = Onboardings::Step.new(onboardings_step_params)

    respond_to do |format|
      if @onboardings_step.save
        format.html { redirect_to edit_onboardings_objective_url(@onboardings_step.objective), notice: "Step was successfully created." }
        format.json { render :show, status: :created, location: @onboardings_step }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @onboardings_step.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /onboardings/steps/1 or /onboardings/steps/1.json
  def update
    respond_to do |format|
      if @onboardings_step.update(onboardings_step_params)
        format.html { redirect_to edit_onboardings_objective_url(@onboardings_step.objective), notice: "Step was successfully updated." }
        format.json { render :show, status: :ok, location: @onboardings_step }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @onboardings_step.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /onboardings/steps/1 or /onboardings/steps/1.json
  def destroy
    @onboardings_step.destroy

    respond_to do |format|
      format.html { redirect_to edit_onboardings_objective_url(@onboardings_step.objective), notice: "Step was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_onboardings_step
      @onboardings_step = Onboardings::Step.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def onboardings_step_params
      params.require(:onboardings_step).permit(:objective_id, :resource_global_id, :resource_type)
    end
end

app/controllers/onboardings/tour_steps_controller.rb
class Onboardings::TourStepsController < ApplicationController

  def index
    @onboardings_objective = Onboardings::Objective.find(params[:objective_id])
    @current_step_id = :start

    render :show
  end
  
  def show
    @onboardings_objective = Onboardings::Objective.find(params[:objective_id])

    if params[:id] == "start"
      @current_step_id = params[:id].to_sym
    elsif params[:id] == "done"
      redirect_to '/', notice: @onboardings_objective.finished_message
    else
      @onboardings_step = @onboardings_objective.steps.find(params[:id])
      @current_step_id = @onboardings_step.id
    end
    
  end
end

app/helpers/onboardings/objectives_helper.rb
module Onboardings::ObjectivesHelper
end

app/helpers/onboardings/steps_helper.rb
module Onboardings::StepsHelper
end

app/views/onboardings/steps/_form.html.erb
<%= form_with(model: onboardings_step) do |form| %>
  <% if onboardings_step.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(onboardings_step.errors.count, "error") %> prohibited this onboardings_step from being saved:</h2>

      <ul>
        <% onboardings_step.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.hidden_field :objective_id %>
    <h3>Objective: <%= onboardings_step.objective.name %></h3>
  </div>

  <div>
    <%= form.label :resource_global_id, "Resource", style: "display: block" %>
    <%= form.collection_select :resource_global_id, Cms::Page.all + News::Post.all, :to_global_id, :label_for_step, include_blank: true %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/onboardings/steps/_step.html.erb
<div id="<%= dom_id step %>">
  <p>
    <strong>List:</strong>
    <%= step.objective_id %>
  </p>

  <p>
    <strong>Resource:</strong>
    (<%= step.resource.class %>)
    <%= step.resource.try(:name) || step.resource.try(:title) || step.resource.try(:subject) %>
  </p>

</div>

app/views/onboardings/steps/edit.html.erb
<h1>Editing step</h1>

<%= render "form", onboardings_step: @onboardings_step %>

<br>

<div>
  <%= link_to "Back to Parent Objective", edit_onboardings_objective_path(@onboardings_step.objective) %>
</div>

app/views/onboardings/steps/index.html.erb
<h1>Steps</h1>

<div id="onboardings_steps">
  <% @onboardings_steps.each do |onboardings_step| %>
    <%= render onboardings_step %>
    <p>
      <%= link_to "Show this step", onboardings_step %>
    </p>
  <% end %>
</div>

<%= link_to "New step", new_onboardings_step_path %>

app/views/onboardings/steps/new.html.erb
<h1>New step</h1>

<%= render "form", onboardings_step: @onboardings_step %>

<br>

<div>

  <%= link_to "Back to Parent Objective", edit_onboardings_objective_path(@onboardings_step.objective) %>
</div>

app/views/onboardings/steps/show.html.erb
<%= render @onboardings_step %>

<div>
  <%= link_to "Edit this step", edit_onboardings_step_path(@onboardings_step) %> |
  <%= link_to "Back to steps", onboardings_steps_path %>

  <%= button_to "Destroy this step", @onboardings_step, method: :delete %>
</div>