config/routes.rb
Rails.application.routes.draw do
  root_controller = 'cms/pages#home'
  root root_controller
  # match '/*' => root_controller, via: :options
  namespace :onboardings do
    resources :objectives do
      resources :tour_steps, only: [:index, :show]
    end
    resources :steps
  end
  namespace :cms do
    resources :pages do
      collection do
        get :home
      end
    end
  end
  namespace :news do
    resources :posts
  end
  namespace :media_center do
    resources :files
  end
  
  get "sessions/create"
  get "sessions/destroy"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/cms.rb
module Cms
  def self.table_name_prefix
    "cms_"
  end
end

app/models/cms/page.rb
class Cms::Page < ApplicationRecord
def label_for_step(with_class: true)
    label = title
    label += " [#{self.class}]" if with_class
    label
  end
end

app/controllers/cms/pages_controller.rb
class Cms::PagesController < ApplicationController
  before_action :set_cms_page, only: %i[show edit update destroy]

  def home
    @cms_page = Cms::Page.first
  end

  # GET /cms/pages or /cms/pages.json
  def index
    @cms_pages = Cms::Page.all
  end

  # GET /cms/pages/1 or /cms/pages/1.json
  def show; end

  # GET /cms/pages/new
  def new
    @cms_page = Cms::Page.new
  end

  # GET /cms/pages/1/edit
  def edit; end

  # POST /cms/pages or /cms/pages.json
  def create
    @cms_page = Cms::Page.new(cms_page_params)

    respond_to do |format|
      if @cms_page.save
        format.html { redirect_to cms_page_url(@cms_page), notice: 'Page was successfully created.' }
        format.json { render :show, status: :created, location: @cms_page }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @cms_page.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cms/pages/1 or /cms/pages/1.json
  def update
    respond_to do |format|
      if @cms_page.update(cms_page_params)
        format.html { redirect_to cms_page_url(@cms_page), notice: 'Page was successfully updated.' }
        format.json { render :show, status: :ok, location: @cms_page }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @cms_page.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cms/pages/1 or /cms/pages/1.json
  def destroy
    @cms_page.destroy

    respond_to do |format|
      format.html { redirect_to cms_pages_url, notice: 'Page was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_cms_page
    @cms_page = Cms::Page.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def cms_page_params
    params.require(:cms_page).permit(:title, :content)
  end
end

app/helpers/cms/pages_helper.rb
module Cms::PagesHelper
end

app/views/cms/pages/_form.html.erb
<div class="form-container">
  <%= form_with(model: cms_page) do |form| %>
    <% if cms_page.errors.any? %>
      <div class="error-container">
        <h2><%= pluralize(cms_page.errors.count, "error") %> prohibited this cms_page from being saved:</h2>
  
        <ul>
          <% cms_page.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  
    <div>
      <%= form.label :title, style: "display: block" %>
      <%= form.text_field :title %>
    </div>
  
    <div>
      <%= form.label :content, style: "display: block" %>
      <%= form.text_area :content %>
    </div>
  
    <div>
      <%= form.submit %>
    </div>
  <% end %>
</div>

app/views/cms/pages/_page.html.erb
<div id="<%= dom_id page %>">
  <h1>
    <%= page.title %>
  </h1>

  <div class="cms-page__content">
    <%= page.content.html_safe %>
  </div>

</div>

app/views/cms/pages/edit.html.erb
<%= link_to "<i class='fas fa-arrow-left back-icon'></i> Back to pages".html_safe, cms_pages_path, class: "back-link" %>

<h1>Editing page</h1>

<%= render "form", cms_page: @cms_page %>

<br>

<div>
  <%= link_to "Show this page", @cms_page, class: "post-link" %>
</div>

app/views/cms/pages/home.html.erb
<div class="homepage">
    <div class="homepage__header">
        <h1>Welcome to Mini Hive!</h1>
        <p>Your one-stop platform for all things Miniature!</p>
    </div>
    
    <div class="homepage__content">
        <h2>Let's Get started</h2>
        <p><b>Try our onboarding paths and let us guide through what Mini Hive can offer you!</b></p>
        <% Onboardings::Objective.all.each do |objective| %>
          <h3><b>
            👉
            <%= link_to objective.name, onboardings_objective_tour_steps_path(objective) %>
            👈
          </b></h3>
        <% end %>
        <p>❤️</p>
        <h2>About Mini Hive</h2>
        <p>Mini Hive is the ultimate resource for miniature enthusiasts. From intricate models to tiny homes, we cover everything you need to start or enhance your miniature journey. Stay connected with us as we bring the world of miniatures to your fingertips!</p>
        <svg height="100" width="100">
  <circle cx="50" cy="50" r="40" stroke="black" stroke-width="3" fill="red" />
</svg>


        <h2>Our Miniature Collections</h2>
        <p>Explore our vast collections of hand-crafted miniatures - each piece uniquely designed and carefully constructed to bring joy to our community of miniaturists. Join us today and discover the wonderful world of miniatures!</p>
        <svg height="100" width="100">
  <polygon points="50,5 95,95 5,95" stroke="black" stroke-width="1" fill="blue"/>
</svg>


        <h2>Join the Mini Hive Community</h2>
        <p>Be a part of our growing community of miniature enthusiasts! Share your creations, get inspired, and learn from others in the Mini Hive community. Join us today!</p>
       <svg height="100" width="100">
  <polygon points="50,5 20,95 95,35 5,35 80,95" stroke="black" stroke-width="1" fill="green"/>
</svg>

    </div>
</div>

app/views/cms/pages/index.html.erb
<h1>Pages <%= "\u{1F3D7}" %></h1>

<% if current_user.admin? %>
  <p><%= link_to "New page", new_cms_page_path, class: "new-post-link" %></p>
<%end%>

<div id="cms_pages">
  <% @cms_pages.each do |cms_page| %>
    <div id="<%= dom_id cms_page %>" class="post">
      <p>
        <strong>Title:</strong>
        <%= cms_page.title %>
      </p>
    
      <p>
        <strong>Content:</strong>
        <%= strip_tags(cms_page.content)[0..100] %> ...
      </p>
    </div>
    <p>
      <%= link_to "Show this page", cms_page, class: "post-link" %>
    </p>
  <% end %>
</div>

app/views/cms/pages/new.html.erb
<div>
  <%= link_to "<i class='fas fa-arrow-left back-icon'></i> Back to pages".html_safe, cms_pages_path, class: "back-link" %>
</div>

<h1>New page</h1>

<%= render "form", cms_page: @cms_page %>

app/views/cms/pages/show.html.erb
<% if current_user.admin? %>
  <div>
    <%= link_to "<i class='fas fa-arrow-left back-icon'></i> Back to pages".html_safe, cms_pages_path, class: "back-link" %>
  </div>
<%end%>

<%= render @cms_page %>

<% if current_user.admin? %>
  <div class="actions-container">
    <%= link_to "Edit this page", edit_cms_page_path(@cms_page), class: "post-link" %>
    <%= button_to "Destroy this page", @cms_page, method: :delete, class: "destroy-btn" %>
  </div>
<%end%>