config/routes.rb
Rails.application.routes.draw do
  root_controller = 'cms/pages#home'
  root root_controller
  # match '/*' => root_controller, via: :options
  namespace :onboardings do
    resources :objectives do
      resources :tour_steps, only: [:index, :show]
    end
    resources :steps
  end
  namespace :cms do
    resources :pages do
      collection do
        get :home
      end
    end
  end
  namespace :news do
    resources :posts
  end
  namespace :media_center do
    resources :files
  end
  
  get "sessions/create"
  get "sessions/destroy"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cms.rb
module Cms
  def self.table_name_prefix
    "cms_"
  end
end

app/models/cms/page.rb
class Cms::Page < ApplicationRecord
def label_for_step(with_class: true)
    label = title
    label += " [#{self.class}]" if with_class
    label
  end
end

app/models/media_center.rb
module MediaCenter
  def self.table_name_prefix
    "media_center_"
  end
end

app/models/media_center/file.rb
class MediaCenter::File < ApplicationRecord
end

app/models/news.rb
module News
  def self.table_name_prefix
    "news_"
  end
end

app/models/news/post.rb
class News::Post < ApplicationRecord
  def label_for_step(with_class: true)
    label = subject
    label += " [#{self.class}]" if with_class
    label
  end
end

app/models/onboardings.rb
module Onboardings
  def self.table_name_prefix
    "onboardings_"
  end
end

app/models/onboardings/objective.rb
class Onboardings::Objective < ApplicationRecord
  has_many :steps, dependent: :destroy

  validates :name, :description, presence: true
end

app/models/onboardings/step.rb
class Onboardings::Step < ApplicationRecord
  belongs_to :objective
  belongs_to :resource, polymorphic: true

  validates :objective, :resource, presence: true

  def resource_global_id
    self.resource&.to_global_id
  end

  def resource_global_id=(global_id)
    self.resource = GlobalID::Locator.locate global_id
  end
end

app/models/user.rb
class User
  USER_TYPES = %w[
    user
    admin
    visitor
  ].freeze

  def initialize(user_type:)
    raise WrongUserTypeError unless user_type.in?(USER_TYPES)

    @user_type = user_type
  end

  def name
    if admin?
      'MyAdmin'
    else
      'MyUser'
    end
  end

  def admin?
    @user_type == 'admin'
  end

  def user?
    @user_type == 'user'
  end

  def connected?
    @user_type != 'visitor'
  end

  def visitor?
    @user_type == 'visitor'
  end

  class WrongUserTypeError < StandardError; end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
end

app/controllers/cms/pages_controller.rb
class Cms::PagesController < ApplicationController
  before_action :set_cms_page, only: %i[show edit update destroy]

  def home
    @cms_page = Cms::Page.first
  end

  # GET /cms/pages or /cms/pages.json
  def index
    @cms_pages = Cms::Page.all
  end

  # GET /cms/pages/1 or /cms/pages/1.json
  def show; end

  # GET /cms/pages/new
  def new
    @cms_page = Cms::Page.new
  end

  # GET /cms/pages/1/edit
  def edit; end

  # POST /cms/pages or /cms/pages.json
  def create
    @cms_page = Cms::Page.new(cms_page_params)

    respond_to do |format|
      if @cms_page.save
        format.html { redirect_to cms_page_url(@cms_page), notice: 'Page was successfully created.' }
        format.json { render :show, status: :created, location: @cms_page }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @cms_page.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cms/pages/1 or /cms/pages/1.json
  def update
    respond_to do |format|
      if @cms_page.update(cms_page_params)
        format.html { redirect_to cms_page_url(@cms_page), notice: 'Page was successfully updated.' }
        format.json { render :show, status: :ok, location: @cms_page }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @cms_page.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cms/pages/1 or /cms/pages/1.json
  def destroy
    @cms_page.destroy

    respond_to do |format|
      format.html { redirect_to cms_pages_url, notice: 'Page was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_cms_page
    @cms_page = Cms::Page.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def cms_page_params
    params.require(:cms_page).permit(:title, :content)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    set_current_user(params[:user_type])

    redirect_back fallback_location: '/', notice: "Welcome #{current_user.name}"
  end

  def destroy
    session[:user] = nil
    redirect_back fallback_location: '/', notice: 'See you again !'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/c_s_s_helper.rb
module CSSHelper
  def class_names(*args)
    ClassNames.call(*args)
  end
end

app/helpers/cms/pages_helper.rb
module Cms::PagesHelper
end

app/helpers/news/posts_helper.rb
module News::PostsHelper
end

app/helpers/onboardings/steps_helper.rb
module Onboardings::StepsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    user_data = session[:user]
    if @_current_user
      @_current_user
    elsif user_data.present?
      @_current_user = User.new(**user_data.symbolize_keys)
    else
      @_current_user = User.new(user_type: 'visitor')
    end
  end

  def set_current_user(user_type)
    user = User.new(user_type:)
    session[:user] = user.as_json
    @_current_user = user
  end
end

app/views/layouts/_menu.html.erb
<nav>
    <%= link_to "Home", "/", class: class_names(active: request.path == "/") %>
    <%= link_to "News", news_posts_path, class: class_names(active: request.path.match?(/\/news/)) %>
    <%= link_to "Media Center", media_center_files_path, class: class_names(active: request.path.match?(/\/media_center/)) %>
    

    <% Cms::Page.all.each do |page| %>
      <%= link_to page.title, cms_page_path(page), class: class_names(active: request.path == cms_page_path(page)) %>
    <%end%>
    
    <div class="right-links">
        <% if current_user.connected? %>
            <% if current_user.admin? %>
                <%= link_to "CMS", cms_pages_path, class: class_names(active: request.path.match?(/\/cms/)) %>
                <%= link_to "Onboardings", onboardings_objectives_path, class: class_names(active: request.path.match?(/\/onboardings/)) %>
            <%end%>
            <%= link_to sessions_destroy_path do %>
                <i class="fas fa-circle-xmark"></i> <%= current_user.name %>
            <%end%>
        <% else %>
            <%= link_to sessions_create_path(user_type: :user) do %>
                <i class='fas fa-user'></i> Log as user
            <%end%>
            <%= link_to sessions_create_path(user_type: :admin) do %>
                <i class='fas fa-user-shield'></i> Log as admin
            <%end%>
        <%end%>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsRuby3</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application" %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">

    <script src="https://unpkg.com/vue@3.2.36/dist/vue.global.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/vue3-sfc-loader/dist/vue3-sfc-loader.js"></script>
    <script src="https://unpkg.com/axios@1.4.0/dist/axios.min.js"></script>
  </head>

  <body>
    <%= render "layouts/menu" %>
    <% flash.each do |type, msg| %>
      <div>
          <p class="flash flash--<%= type %>"><%= msg %></p>
      </div>
    <% end %>
    <div class="main-content">
      <%= yield %>
    </div>
  </body>
</html>